HelpingHands/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls',namespace="base")),
]

base/urls.py
from django.urls import path
from .import views


app_name ='base'

urlpatterns = [
    path('',views.home,name='home'),
    path('donate/',views.donate,name='donate'),
    path('charge/', views.charge, name="charge"),
    path('thanks/<str:args>/',views.thanks,name='thanks')
]

base/models.py
from django.db import models

# Create your models here.

HelpingHands/base/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import JsonResponse
from django.core.mail import send_mail
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
import stripe
import json
# Create your views here.

stripe.api_key ='sk_test_51Gz20rIPDW7FrALVrHaj6LC99kLu5B24hSaFVAwRx4M5nvCNAkeE3oishiarGh6Mho92k9P42kE7A7zlppAiMNRI00z8Klep0N'
print(stripe.api_key)


def home(request):
	return render(request, 'base/home.html')
     
def donate(request):
	return render(request, 'base/donate.html')

def charge(request):
	if request.method == 'POST':
		d_amount = int(request.POST['amount'])
		email=request.POST['email']
		name=request.POST['name']
		customer = stripe.Customer.create(
			email=request.POST['email'],
			name=request.POST['name'],
			source=request.POST['stripeToken']
			)

		charge = stripe.Charge.create(
			customer=customer,
			amount=d_amount*100,
			currency='inr',
			description="Donation",
			)
		our_customer=charge.get("customer")

		# invoice_create_item =stripe.InvoiceItem.create(
  		# customer=our_customer,
		# amount=d_amount*100,
		# currency='inr'
		# )

		# invoice = stripe.Invoice.create(
		# customer=our_customer,
		# collection_method='charge_automatically',
		# description="Donation for Helping Hands",
		# )
		payment_intent=stripe.PaymentIntent.create(
			amount=d_amount*100,
			currency='inr',
			payment_method_types=['card'],
			receipt_email=email,
			)
		print(payment_intent)
	return redirect(reverse('base:thanks', args=[d_amount]))

def thanks(request,args):
	amount = args
	return render(request, 'base/done.html', {'amount':amount})

base/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import JsonResponse
from django.core.mail import send_mail
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
import stripe
import json
# Create your views here.

stripe.api_key ='sk_test_51Gz20rIPDW7FrALVrHaj6LC99kLu5B24hSaFVAwRx4M5nvCNAkeE3oishiarGh6Mho92k9P42kE7A7zlppAiMNRI00z8Klep0N'
# print(stripe.api_key)


def home(request):
	return render(request, 'base/home.html')
     
def donate(request):
	return render(request, 'base/donate.html')

def charge(request):
	if request.method == 'POST':
		d_amount = int(request.POST['amount'])
		email=request.POST['email']
		name=request.POST['name']
		customer = stripe.Customer.create(
			email=request.POST['email'],
			name=request.POST['name'],
			source=request.POST['stripeToken']
			)

		charge = stripe.Charge.create(
			customer=customer,
			amount=d_amount*100,
			currency='inr',
			description="Donation",
			)
		our_customer=charge.get("customer")

		# invoice_create_item =stripe.InvoiceItem.create(
  		# customer=our_customer,
		# amount=d_amount*100,
		# currency='inr'
		# )

		# invoice = stripe.Invoice.create(
		# customer=our_customer,
		# collection_method='charge_automatically',
		# description="Donation for Helping Hands",
		# )
		payment_intent=stripe.PaymentIntent.create(
			amount=d_amount*100,
			currency='inr',
			payment_method_types=['card'],
			receipt_email=email,
			)
		# print(payment_intent)
	return redirect(reverse('base:thanks', args=[d_amount]))

def thanks(request,args):
	amount = args
	return render(request, 'base/done.html', {'amount':amount})

HelpingHands/base/templates/base/donate.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
Donate
{% endblock title %}
{% block scripts %}
{% endblock scripts %}

{% block content %}
<style>
	/* left and right of donation page  */
#container{
  width:1200px;
  margin:0 auto;
  padding-top: 3%;
}
.column-6{
  width: 50%;
  float:left;
}
  #left-wrapper{
      display: flex;
      background-color: #4F8A8B;
      box-shadow: 0 1px 3px 0 black;
      border-radius: 20px 0px 0px 20px;
      border: 1px solid transparent;
      padding: 30px;	
	    width:600px;
      height: 600px;
      padding:50px;
  }
    
  #left-wrapper-head{
    color:#fff;
    font-family: 'Montserrat', sans-serif;
    text-align: center;
    font-size:24px;
  }
  #left-wrapper-content{
    font-family: 'Montserrat', sans-serif;
    text-align: justify;
    font-size:20px;
  }
    #about-btn{
     width:20vw;
     height:7vh;
    background-color:#222831;
    border-radius: 10px;
    color: #EEEEEE;
    text-align: center;
    font-family: 'Montserrat', sans-serif;
  }
  #about-btn > p{
    padding: 20px;
  }

  #right-wrapper{
    background-color: #EEEEEE;
      border-radius: 0px 20px 20px 0px;
      border: 1px solid transparent;
    padding: 30px;
    width:600px;
    box-shadow: 0 1px 3px 0 black;
    display:flex;
    flex-direction: column;
    flex-wrap: wrap;
    justify-content: center;
    align-items: center;
    height: 600px;
  }

  #right-wrapper-head{
    color: #000000;
    font-family: 'Montserrat', sans-serif;
    text-align: center;
    font-size: 24px;
  }

  @media screen and (max-width:1200px){
    #container{
      width:80%;
    }

    .column-6{
      width: 100%;
    }
  }

  @media screen and (max-width:800px){
    #container{
      width:100%;
    }
  }

  /* stripe element styling */

  .StripeElement {
    box-sizing: border-box;

    height: 40px;

    padding: 10px 12px;

    border: 1px solid transparent;
    border-radius: 4px;
    background-color: white;

    box-shadow: 0 1px 3px 0 #e6ebf1;
    -webkit-transition: box-shadow 150ms ease;
    transition: box-shadow 150ms ease;
  }

  .StripeElement--focus {
    box-shadow: 0 1px 3px 0 #cfd7df;
  }

  .StripeElement--invalid {
    border-color: #fa755a;
  }

  .StripeElement--webkit-autofill {
    background-color: #fefde5 !important;
  }

/* form styling */

  .form-field-12{
    width: 100%;
    margin-bottom: 10px;
    padding-top: 5px;
  }
  .form-field-6{
    width: 100%;
    margin-bottom: 10px;
  }
  input {
    border-radius: 6px;
    margin-bottom: 6px;
    border: 1px solid rgba(50, 50, 93, 0.1);
	width: 100px;
    height: 44px;
    font-size: 16px;
    width: 100%;
    background: #4f8a8b4f;
    align-content: center;
  }

  input::placeholder {
    color: #9fa1a6;
  }
  .result-message {
    line-height: 22px;
    font-size: 16px;
  }
  .result-message a {
    color: rgb(89, 111, 214);
    font-weight: 600;
    text-decoration: none;
  }
  .hidden {
    display: none;
  }
  #card-error {
    color: rgb(105, 115, 134);
    text-align: left;
    font-size: 13px;
    line-height: 17px;
    margin-top: 12px;
  }
  #card-element {
    border-radius: 6px ;
    padding: 12px;
    height: 44px;
    width: 100%;
    background: #4f8a8b4f;
  }
  .myButton{
    width:20vw;
     height:7vh;
    background-color:#222831;
    border-radius: 10px;
    color: #EEEEEE;
    text-align: center;
    font-family: 'Montserrat', sans-serif;
  }
  .myButton:hover {
    opacity: .6;
  }

</style>
<div id="container">
	<div class="column-6">
		<div id="left-wrapper">
			<div id="left-wrapper-head">
				<h3>Information</h3>
			</div>
			<hr>
			<div id="left-wrapper-content">
				<p>
          For more than a year now we have been distributing free Covid-19 Care-kits to people who are in need.
        </p>
        <p>
          We never compromise on the quality of things we give away and yes they cost a lot your small contribution to our non-profit initiative will be very beneficial!
	        <br>
        </p>
        <p>
          We give good quality masks, hand sanitizers, multivitamins tablets, and some guides.
          <br>
          Thanks in advance.
				</p>
			</div>
		</div>
	</div>
	<div class="column-6">
		<div id="right-wrapper">
			<div id="right-wrapper-head">
				One Time Donation
			</div>
			<hr>
			<form action="{% url 'base:charge' %}"  method="post" id="payment-form">
				{% csrf_token %}
				<div class="form-field-12">
					<div class="form-field-6">
					  <input required type="integer" name="amount" placeholder="Amount">
				  </div>
				</div>
				<div class="form-field-6">
				  <input required type="text" name="name" placeholder="Name">
			  </div>
				<div class="form-field-6">
					<input required type="text" name="email" placeholder="Email">
				</div>
			  <div class="form-row">
				<label for="card-element">
				  Credit or debit card
				</label>
				<div id="card-element">
				  <!-- A Stripe Element will be inserted here. -->
				</div>
			
				<!-- Used to display form errors. -->
				<div id="card-errors" role="alert"></div>
			  </div>
			  
			  <div style="clear:left"></div>
			  <br>
				 <input  class="myButton" type="submit" value="Submit Payment" name="">
			
			</form>
		</div>
	</div>
</div>


	<script>
    var stripe = Stripe('pk_test_51Gz20rIPDW7FrALV9nHGF02My5bHPpLXia3mV4BMqofdwgZJ4jOt7mFGM9wnAGhlxy0s85lVnW1Tn9a43J162Chp00rwYE95Gf');

		// Create an instance of Elements.
		var elements = stripe.elements();

		// Custom styling can be passed to options when creating an Element.
		// (Note that this demo uses a wider set of styles than the guide below.)
		var style = {
		  base: {
		    color: '#32325d',
		    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
		    fontSmoothing: 'antialiased',
		    fontSize: '16px',
		    '::placeholder': {
		      color: '#aab7c4',
		    }
		  },
		  invalid: {
		    color: '#fa755a',
		    iconColor: '#fa755a'
		  }
		};

		// Create an instance of the card Element.
		var card = elements.create('card', {style: style});

		// Add an instance of the card Element into the `card-element` <div>.
		card.mount('#card-element');

		// Handle real-time validation errors from the card Element.
		card.addEventListener('change', function(event) {
		  var displayError = document.getElementById('card-errors');
		  if (event.error) {
		    displayError.textContent = event.error.message;
		  } else {
		    displayError.textContent = '';
		  }
		});

		// Handle form submission.
		var form = document.getElementById('payment-form');
		form.addEventListener('submit', function(event) {
		  event.preventDefault();

		  stripe.createToken(card).then(function(result) {
		    if (result.error) {
		      // Inform the user if there was an error.
		      var errorElement = document.getElementById('card-errors');
		      errorElement.textContent = result.error.message;
		    } else {
		      // Send the token to your server.
		      stripeTokenHandler(result.token);
		    }
		  });
		});

		// Submit the form with the token ID.
		function stripeTokenHandler(token) {
		  // Insert the token ID into the form so it gets submitted to the server
		  var form = document.getElementById('payment-form');
		  var hiddenInput = document.createElement('input');
		  hiddenInput.setAttribute('type', 'hidden');
		  hiddenInput.setAttribute('name', 'stripeToken');
		  hiddenInput.setAttribute('value', token.id);
		  form.appendChild(hiddenInput);

		  // Submit the form
		  form.submit();
		}
  </script>
{% endblock content %}

base/templates/base/donate.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
Donate
{% endblock title %}
{% block scripts %}
{% endblock scripts %}

{% block content %}
<style>
	/* left and right of donation page  */
#container{
  width:1200px;
  margin:0 auto;
  padding-top: 3%;
}
.column-6{
  width: 50%;
  float:left;
}
  #left-wrapper{
      display: flex;
      flex-direction: column;
      background-color: #4F8A8B;
      box-shadow: 0 1px 3px 0 black;
      border-radius: 20px 0px 0px 20px;
      border: 1px solid transparent;
      padding: 30px;	
	    width:600px;
      height: 600px;
      padding:50px;
  }
    
  #left-wrapper-head{
    color:#fff;
    font-family: 'Montserrat', sans-serif;
    text-align: center;
    font-size:24px;
  }
  #left-wrapper-content{
    font-family: 'Montserrat', sans-serif;
    text-align: justify;
    font-size:20px;
  }
    #about-btn{
     width:20vw;
     height:7vh;
    background-color:#222831;
    border-radius: 10px;
    color: #EEEEEE;
    text-align: center;
    font-family: 'Montserrat', sans-serif;
  }
  #about-btn > p{
    padding: 20px;
  }

  #right-wrapper{
    background-color: #EEEEEE;
      border-radius: 0px 20px 20px 0px;
      border: 1px solid transparent;
    padding: 30px;
    width:600px;
    box-shadow: 0 1px 3px 0 black;
    display:flex;
    flex-direction: column;
    flex-wrap: wrap;
    justify-content: center;
    align-items: center;
    height: 600px;
  }

  #right-wrapper-head{
    color: #000000;
    font-family: 'Montserrat', sans-serif;
    text-align: center;
    font-size: 24px;
  }

  @media screen and (max-width:1200px){
    #container{
      width:80%;
    }

    .column-6{
      width: 100%;
    }
  }

  @media screen and (max-width:800px){
    #container{
      width:100%;
    }
  }

  /* stripe element styling */

  .StripeElement {
    box-sizing: border-box;

    height: 40px;

    padding: 10px 12px;

    border: 1px solid transparent;
    border-radius: 4px;
    background-color: white;

    box-shadow: 0 1px 3px 0 #e6ebf1;
    -webkit-transition: box-shadow 150ms ease;
    transition: box-shadow 150ms ease;
  }

  .StripeElement--focus {
    box-shadow: 0 1px 3px 0 #cfd7df;
  }

  .StripeElement--invalid {
    border-color: #fa755a;
  }

  .StripeElement--webkit-autofill {
    background-color: #fefde5 !important;
  }

/* form styling */

  .form-field-12{
    width: 100%;
    margin-bottom: 10px;
    padding-top: 5px;
  }
  .form-field-6{
    width: 100%;
    margin-bottom: 10px;
  }
  input {
    border-radius: 6px;
    margin-bottom: 6px;
    border: 1px solid rgba(50, 50, 93, 0.1);
	width: 100px;
    height: 44px;
    font-size: 16px;
    width: 100%;
    background: #4f8a8b4f;
    align-content: center;
  }

  input::placeholder {
    color: #9fa1a6;
  }
  .result-message {
    line-height: 22px;
    font-size: 16px;
  }
  .result-message a {
    color: rgb(89, 111, 214);
    font-weight: 600;
    text-decoration: none;
  }
  .hidden {
    display: none;
  }
  #card-error {
    color: rgb(105, 115, 134);
    text-align: left;
    font-size: 13px;
    line-height: 17px;
    margin-top: 12px;
  }
  #card-element {
    border-radius: 6px ;
    padding: 12px;
    height: 44px;
    width: 100%;
    background: #4f8a8b4f;
  }
  .myButton{
    width:20vw;
     height:7vh;
    background-color:#222831;
    border-radius: 10px;
    color: #EEEEEE;
    text-align: center;
    font-family: 'Montserrat', sans-serif;
  }
  .myButton:hover {
    opacity: .6;
  }

</style>
<div id="container">
	<div class="column-6">
		<div id="left-wrapper">
			<div id="left-wrapper-head">
				<h3>Information</h3>
			</div>
			<hr>
			<div id="left-wrapper-content">
				<p>
          For more than a year now we have been distributing free Covid-19 Care-kits to people who are in need.
        </p>
        <p>
          We never compromise on the quality of things we give away and yes they cost a lot your small contribution to our non-profit initiative will be very beneficial!
	        <br>
        </p>
        <p>
          We give good quality masks, hand sanitizers, multivitamins tablets, and some guides.
          <br>
          Thanks in advance.
				</p>
			</div>
		</div>
	</div>
	<div class="column-6">
		<div id="right-wrapper">
			<div id="right-wrapper-head">
				One Time Donation
			</div>
			<hr>
			<form action="{% url 'base:charge' %}"  method="post" id="payment-form">
				{% csrf_token %}
				<div class="form-field-12">
					<div class="form-field-6">
					  <input required type="integer" name="amount" placeholder="Amount">
				  </div>
				</div>
				<div class="form-field-6">
				  <input required type="text" name="name" placeholder="Name">
			  </div>
				<div class="form-field-6">
					<input required type="text" name="email" placeholder="Email">
				</div>
			  <div class="form-row">
				<label for="card-element">
				  Credit or debit card
				</label>
				<div id="card-element">
				  <!-- A Stripe Element will be inserted here. -->
				</div>
			
				<!-- Used to display form errors. -->
				<div id="card-errors" role="alert"></div>
			  </div>
			  
			  <div style="clear:left"></div>
			  <br>
				 <input  class="myButton" type="submit" value="Submit Payment" name="">
			
			</form>
		</div>
	</div>
</div>


	<script>
    var stripe = Stripe('pk_test_51Gz20rIPDW7FrALV9nHGF02My5bHPpLXia3mV4BMqofdwgZJ4jOt7mFGM9wnAGhlxy0s85lVnW1Tn9a43J162Chp00rwYE95Gf');

		// Create an instance of Elements.
		var elements = stripe.elements();

		// Custom styling can be passed to options when creating an Element.
		// (Note that this demo uses a wider set of styles than the guide below.)
		var style = {
		  base: {
		    color: '#32325d',
		    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
		    fontSmoothing: 'antialiased',
		    fontSize: '16px',
		    '::placeholder': {
		      color: '#aab7c4',
		    }
		  },
		  invalid: {
		    color: '#fa755a',
		    iconColor: '#fa755a'
		  }
		};

		// Create an instance of the card Element.
		var card = elements.create('card', {style: style});

		// Add an instance of the card Element into the `card-element` <div>.
		card.mount('#card-element');

		// Handle real-time validation errors from the card Element.
		card.addEventListener('change', function(event) {
		  var displayError = document.getElementById('card-errors');
		  if (event.error) {
		    displayError.textContent = event.error.message;
		  } else {
		    displayError.textContent = '';
		  }
		});

		// Handle form submission.
		var form = document.getElementById('payment-form');
		form.addEventListener('submit', function(event) {
		  event.preventDefault();

		  stripe.createToken(card).then(function(result) {
		    if (result.error) {
		      // Inform the user if there was an error.
		      var errorElement = document.getElementById('card-errors');
		      errorElement.textContent = result.error.message;
		    } else {
		      // Send the token to your server.
		      stripeTokenHandler(result.token);
		    }
		  });
		});

		// Submit the form with the token ID.
		function stripeTokenHandler(token) {
		  // Insert the token ID into the form so it gets submitted to the server
		  var form = document.getElementById('payment-form');
		  var hiddenInput = document.createElement('input');
		  hiddenInput.setAttribute('type', 'hidden');
		  hiddenInput.setAttribute('name', 'stripeToken');
		  hiddenInput.setAttribute('value', token.id);
		  form.appendChild(hiddenInput);

		  // Submit the form
		  form.submit();
		}
  </script>
{% endblock content %}

base/templates/base/done.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
Thanks 
{% endblock title %}
{% block content %}
	<div id="box">
		<h3>Donation successful</h3>
		<img src="{% static "images/tick.png" %}"  height="200">
		<h4>Thank you for donating &#x20B9;{{amount}}</h4>
		<p>You should receive a receipt to the email you provided shortly :)</p>
	</div>
{% endblock content %}

base/templates/base/home.html
{% extends "layout.html" %}
{% load static %}
{% block title %}
Home
{% endblock title %}
{% block content %}

<div class="main-content">
    <div class="header-container">
        <div class="head-left">
            <img class="mylogo" src="{% static "images/icon.png" %}"  height="80">
            <h1 class="title-name">Helping Hands</h1>
        </div>
        <div class="head-right">
            <h5 id="about">Get To Know About Us</h5>
        </div>

    </div>
    <br>
    <div class="main-box">
        <div class="left">
            <img class="hands" src="{% static "images/hands.png" %}" height=300>
        </div>
        <div class="right">
            <p class="quote">“  No one has ever 
                become poor by giving ” 
                <br>
                -Anne Frank
                </p>
            <p class="tag-text">Let's do what we can to stay safe and help others stay safe. </p>
            <div class="btndiv">
                <a href="{% url 'base:donate' %}" >Donate</a>
            </div> 
        </div>    
</div>
<div class="we">
    <p>We give people Covid-19 Care-Kit for Free!!</p>
</div>
<div class="whatwegive">
    <div class="left-kit">
        <img class="hands" src="{% static "images/kit.png" %}" height=310>
    </div>
    <div class="all-items">
        <img class="hands" src="{% static "images/kit-content.gif" %}" height=450>
    </div> 
</div>
<footer>
    <div class="column">
    <a class="footer_title">Helping Hands</a>
    <a>We reachout to people who are in need of help and support them as much as we can</a>
    <a href="#" title="Facebook"><i class="material-icons-round"></i></a>
    <a href="#" title="Instagram"><i class="bi bi-instagram"></i></a>
    <a href="#" title="Twitter"><i class="fa fa-twitter"></i></a>
    </div>
    <div class="column">
    <a class="footer_title">OTHER LINKS</a>
    <a href="#">Privacy Policy</a>
    <a href="#">Terms & Conditions</a>
    <a href="#">Ticket</a>
    <a href="#">Contact Us</a>
    </div>
    <div class="column">
    <a class="footer_title">SHORT CUT</a>
    <a href="">Our Services</a>
    <a href="">Our Blog</a>
    <a href="">Our Projects</a>
    <a href="">About Us</a>
    </div>
    <div class="column">
    <a class="footer_title">GET IN TOUCH</a>
    <a title="Address"><i class="fa fa-map-marker"></i> 007, Rajam Nagar, Tamil nadu, India - 624531</a>
    <a href="emailto:" title="Email"><i class="fa fa-envelope"></i>helpinghands@gmail.com</a>
    <a href="tel:" title="Contact"><i class="fa fa-phone"></i> +(91)-5434-35355</a>
    </div>
    
    <div class="sub-footer">
    © CopyRights 2021 helpinghands || All rights reserved
    </div>
    </footer>
{% endblock content %}

templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon --> 
    <link rel="icon" href="./favicon.ico" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" defer></script>
    <script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
    <!-- Custom js & css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/donate.css' %}">
    <link rel="stylesheet" href="{% static 'css/done.css' %}">
    <!-- <script src="{% static 'javascript/main.js' %}"></script> -->
    {% block scripts %}
    {% endblock scripts %}
    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel+Decorative:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet">
    <!-- stripe -->
    
    <title>Helping Hands | {% block title %}{% endblock title %}</title>
  </head>
  <script src="https://js.stripe.com/v3/"></script>
  <body>
    <div>
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
  </body>
</html>